#!/usr/bin/perl 
my $subrs = "'block' => [qw(at addline cget configure delete 
	                     deletelines insert list names of split trim)],
                 ";
my $methods = 'EnterMethods Tk::eText __FILE__, qw(bbox block compare debug delete 
				dlineinfo get index insert mark scan search
				see tag window xview yview);

';

s/Text/eText/g; 
s/::text/::etext/g; 
s/'window'/$subrs$&/;
s/^(use\s*)?Tk::SubMethods/$methods$&/i;
s/(bootstrap Tk::eText) \$Tk::VERSION/$1/;
